# Copyright 2023 Paion Data. All rights reserved.
---
name: Release

"on":
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: test
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - name: Tag for release
        run: |
          git config --global user.name 'QubitPi'
          git config --global user.email 'jack20191124@proton.me'
          .github/tag-for-release.bash
      - name: Set release version
        run: |
          VERSION=$(git describe)
          npm version $VERSION
      - name: Publish to NPM Packages
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-documentation:
    needs: test
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Messier-61 dependencies so that TypeDoc process source files properly
        run: |
          cd ../
          npm install
      - name: Install doc dependencies
        run: yarn install
      - name: Build documentation
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: QubitPi
          user_email: jack20191124@proton.me
