# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Test

"on":
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  yaml-lint:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionshub/yamllint@main
  markdown-lint:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionshub/markdownlint@main
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: "yes"

  unit-tests:
    name: Run Unit Tests of All Packages
    needs: [yaml-lint, markdown-lint, markdown-link-check]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/messier-61-graph
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm -g install yarn
      - run: yarn install --frozen-lockfile
      - name: Run unit tests
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'  # Avoids "JavaScript heap out of memory" error in CI/CD
        run: yarn test
      - name: Arc tests
        run: |
          cd ./src/neo4j-arc
          rm -rf ../../node_modules/
          npm -g install yarn
          yarn install --frozen-lockfile
          yarn test
          yarn build

  e2e-tests:
    name: Run End-to-End Tests of All Packages
    needs: [unit-tests]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        neo4j-version:
          - 3.5
          - 4.3
          - 4.4
          - 5
        neo4j-edition:
          - community
          - enterprise
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}-${{ matrix.neo4j-edition }}
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
        ports:
          - 7687:7687
          - 7474:7474
    defaults:
      run:
        working-directory: packages/messier-61-graph
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm -g install yarn serve
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: sudo apt-get update
      - run: sudo apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: npx serve -l 8080 dist & npm run wait-on-neo4j && yarn wait-on-dev
      - run: echo "Servers ready!"
      - run: yarn e2e --env server=${{ matrix.neo4j-version }},browser-password=password,edition=${{ matrix.neo4j-edition }}
      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots-${{ matrix.neo4j-version }}-${{ matrix.neo4j-edition }}
          path: |
            packages/messier-61-graph/e2e_tests/screenshots
            packages/messier-61-graph/e2e_tests/videos
